name: Build PVE QEMU with VirGL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          meson \
          ninja-build \
          pkg-config \
          libdrm-dev \
          libepoxy-dev \
          libgbm-dev \
          libx11-dev \
          libxext-dev \
          libxfixes-dev \
          libxcb-dri3-dev \
          libxcb-present-dev \
          libxshmfence-dev \
          libxxf86vm-dev \
          libxrandr-dev \
          cmake \
          python3-dev \
          python3-pip \
          libglib2.0-dev \
          libpixman-1-dev \
          libcap-ng-dev \
          libattr1-dev \
          libaio-dev \
          libbz2-dev \
          liblzo2-dev \
          libzstd-dev \
          uuid-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libfdt-dev \
          libjemalloc-dev \
          libnuma-dev \
          librbd-dev \
          libiscsi-dev \
          libnfs-dev \
          liburing-dev \
          libpmem-dev \
          libdaxctl-dev \
          libslirp-dev \
          libgnutls28-dev \
          libsasl2-dev \
          libvdeplug-dev \
          libvte-2.91-dev \
          libsdl2-dev \
          libpng-dev \
          libjpeg-dev \
          libvncserver-dev \
          libusb-1.0-0-dev \
          libudev-dev \
          libspice-protocol-dev \
          libspice-server-dev \
          libusbredirparser-dev \
          libtasn1-6-dev \
          libvirglrenderer-dev \
          libvulkan-dev \
          libvulkan1 \
          libva-drm2 \
          libva-dev \
          debhelper

    - name: Build virglrenderer
      run: |
        git clone https://gitlab.freedesktop.org/virgl/virglrenderer.git
        cd virglrenderer
        meson build -Dvenus=true -Dvideo=True -Dprefix=/usr
        cd build
        sudo ninja install
        # Update library cache
        sudo ldconfig

    - name: Clone and prepare pve-qemu
      run: |
        git clone https://github.com/proxmox/pve-qemu
        cd pve-qemu
        git submodule update --init --recursive
        cd qemu
        meson subprojects download

    - name: Apply virgl patch
      run: |
        cp virgl.patch pve-qemu/qemu/
        cd pve-qemu/qemu
        patch -p1 < virgl.patch

    - name: Build deb package
      run: |
        cd pve-qemu
        make deb

    - name: Find and list deb files
      id: find_debs
      run: |
        echo "Finding .deb files..."
        find . -name "*.deb" -type f
        echo "deb_files<<EOF" >> $GITHUB_OUTPUT
        find . -name "*.deb" -type f >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Upload deb artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pve-qemu-virgl-debs
        path: |
          **/*.deb
        retention-days: 30

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          pve-qemu/build/*.log
          pve-qemu/qemu/build/*.log
          virglrenderer/build/meson-logs/*.txt
        retention-days: 7
        if-no-files-found: ignore